################################################################################################
# HealthNameTag By WarTechDevs #
# for custom plugins contact RevengeTech#4672 #
# this isnt yet done #
# things todo listed below #
# show health in chat using purechat and pureperms #
# add support for \n #
# add to show rank on name tag basically add support for purechat and pureperms #
# add a healthnametag command to enable and disable for OPS only #
################################################################################################
